version: '2'
services:
    discriminator-app:
        image: discriminator
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://discriminator-postgresql:5432/discriminator
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    discriminator-postgresql:
        extends:
            file: postgresql.yml
            service: discriminator-postgresql
