version: '2'
services:
    discriminator-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/discriminator/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=discriminator
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
